spring.application.name=scm

spring.datasource.url=jdbc:postgresql://localhost:5432/scm
spring.datasource.username=bipanshu
spring.datasource.password=bipanshu544

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect